services:
  auth-service:
    container_name: auth-service
    build:
      context: ./AuthService
    volumes:
      - ./LocalDb:/app/LocalDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todo-network
  todo-service:
    container_name: todo-service
    build:
      context: ./TodoService
    volumes:
      - ./LocalDb:/app/LocalDb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todo-network
    depends_on:
      - auth-service
  api-gateway:
    container_name: api-gateway
    build:
      context: ./ApiGateway
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - todo-network
    depends_on:
      - auth-service
      - todo-service
    
networks:
  todo-network:
    driver: bridge
